### ISSUE TITLE
Modifies files in .svn directories

### ISSUE THREAD

**Issue by turbo2ltr** [rhoerr/supee-6788-toolbox#10]
The analyze step shows that files in .svn directories will be modified. That would be bad.

**Comment by turbo2ltr** [comment]
added 

```
if(strrpos( $file, '.svn' ) !== false)
    continue;   // it's a file in .svn folder
```

At line 433

**Comment by rhoerr** [comment]
Can you wrap that continue in braces and then submit a pull request? Thanks.

**Comment by turbo2ltr** [comment]
I do apologize, I'm not familiar with using github (I've always used svn) and not set up to make PRs. But after the svn hell I've been through today, I think I may need to change that.
