### ISSUE TITLE
PHP Warning  PHP Fatal error

### ISSUE THREAD

**Issue by theskillwithin** [rhoerr/supee-6788-toolbox#18]
not sure if this is an issue or something I am doing wrong.

$ php -f fixSUPEE6788.php -- analyze
PHP Warning:  require_once(abstract.php): failed to open stream: No such file or directory in /var/www/skincarebyalanaupgrade/fixSUPEE6788.php on line 29
PHP Stack trace:
PHP   1. {main}() /var/www/skincarebyalanaupgrade/fixSUPEE6788.php:0

Warning: require_once(abstract.php): failed to open stream: No such file or directory in /var/www/skincarebyalanaupgrade/fixSUPEE6788.php on line 29

Call Stack:
    0.0018     394448   1. {main}() /var/www/skincarebyalanaupgrade/fixSUPEE6788.php:0

PHP Fatal error:  require_once(): Failed opening required 'abstract.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/skincarebyalanaupgrade/fixSUPEE6788.php on line 29
PHP Stack trace:
PHP   1. {main}() /var/www/skincarebyalanaupgrade/fixSUPEE6788.php:0

Fatal error: require_once(): Failed opening required 'abstract.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/skincarebyalanaupgrade/fixSUPEE6788.php on line 29

Call Stack:
    0.0018     394448   1. {main}() /var/www/skincarebyalanaupgrade/fixSUPEE6788.php:0

**Comment by rhoerr** [comment]
Per the directions, you need to put the script inside the `shell` folder. It looks like you have it in the site root.

**Comment by theskillwithin** [comment]
Ah! silly me.  That was the problem.  Thank you!!!
