### ISSUE TITLE
"Newsletter > Newsletter queue": error 404 / Unable to fix it with Dev Toolbox

### ISSUE THREAD

**Issue by albansch** [rhoerr/supee-6788-toolbox#27]
Since I applied the SUPEE-6788 patch to my CE 1.7.0.2 Magento installation, I can't access anymore the page of the admin "Newsletter > Newsletter queue". It results in a 404 error. The admin URL of that page is the following: http://domain.com/shop/index.php/admin/newsletter_queue/index/

I fixed all other blocks & extension with the SUPEE-6788 Developer Toolbox (https://github.com/rhoerr/supee-6788-toolbox), but it cannot fix this specific problem.

Thx for your help, I cant send newsletters anymore...

**Comment by rhoerr** [comment]
Per the readme and instructions, this tool is not a one-step all-inclusive solution to SUPEE-6788 patch problems. We don't guarantee that it will fix every possible situation, nor that it will do so flawlessly. It tells you in the output about any situations it cannot handle automatically; it's up to you (or your support team) to handle any such cases or other errors that result.

If you need help, feel free to reach out to us (contact details in the readme), but any support would be billable.

**Comment by albansch** [comment]
Understood, I was just surprised it couldn't fix such feature as the Newsletter Queue and I was wondering if it was a bug. In fact, I get no output for this specific issue.
Thx for your help anyway, and for this amazingly helpful patch.

**Comment by albansch** [comment]
Hi, I finally found my problem. It was linked to an additional module.
See http://magento.stackexchange.com/questions/90274/ce-1-7-0-2-after-supee-6788-admin-newsletter-newsletter-queue-results/91441#91441
